[package]
name = "rustgrpcdemo"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = "0"
prost = "0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0"

async-stream = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tonic-build = "0"
